spring:
  datasource:
    password: qwe8584951
    minIdle: 5
    initialSize: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://liyue08alibaba.mysql.rds.aliyuncs.com:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: liyue08
    maxActive: 20
logging:
  level:
    mp.dao: trace
    liyue08: warn
  pattern:
    console:
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
